### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sheeep** [1up-lab/contao-page-teaser#1]
Tried to install this extension. It failed miserably.
Maybe it's due to the fact that the repo is empty?

**Comment by bytehead** [comment]
Fixed by a6c27f6c63789ae8f262f0909052f524ea8f0ca0.

**Comment by bytehead** [comment]
btw:
![maybe.](http://img.pandawhale.com/post-31246-maybe-maybe-not-maybe-fuck-you-tQ59.gif)
